# Generated by Django 4.2 on 2023-06-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('HallID', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('HallName', models.TextField()),
                ('Capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('LecturerID', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('LecturerName', models.TextField()),
                ('LecturerPass', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('ProgramID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProgramName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventID', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('EventDateTime', models.DateTimeField(auto_now_add=True)),
                ('HallID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subproject.hall')),
                ('LecturerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subproject.lecturer')),
                ('ProgramID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subproject.program')),
            ],
        ),
    ]
