# Generated by Django 4.2 on 2023-06-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regis',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations_capacity', to='subproject.hall')),
                ('EventDateTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='subproject.event')),
                ('HallName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations_hall', to='subproject.hall')),
                ('LecturerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='subproject.lecturer')),
                ('ProgramName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations_program', to='subproject.program')),
            ],
        ),
    ]
