# Generated by Django 4.2 on 2023-06-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subproject', '0003_rename_hallname_regis_hallid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EventDateTime',
        ),
        migrations.AlterField(
            model_name='program',
            name='ProgramID',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Regis',
        ),
    ]
