# Generated by Django 4.2 on 2023-07-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subproject', '0004_remove_event_eventdatetime_alter_program_programid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='EventTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
